apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-tracker-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: vijaygenius123/exercise-tracker-backend
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8000
